package env

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xlfzxr/tor/internal/config"
)

// ProxyFile is the JSON schema written to XDG_DATA_HOME/torstack/proxy.json.
// Consumers (shell, scripts, Termux apps) can read this without parsing shell.
type ProxyFile struct {
	HTTPProxy   string `json:"http_proxy"`
	HTTPSProxy  string `json:"https_proxy"`
	AllProxy    string `json:"all_proxy"`
	SocksProxy  string `json:"socks_proxy"`
	NoProxy     string `json:"no_proxy"`
	SocksAddr   string `json:"tor_socks_addr"`
	PrivoxyAddr string `json:"privoxy_addr"`
	ControlAddr string `json:"tor_control_addr"`
}

// DataDir returns XDG_DATA_HOME/torstack, fallback ~/.local/share/torstack.
func DataDir() string {
	if v := os.Getenv("XDG_DATA_HOME"); v != "" {
		return filepath.Join(v, "torstack")
	}
	h, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(os.TempDir(), "torstack")
	}
	return filepath.Join(h, ".local", "share", "torstack")
}

// EnvPaths returns destination files for --write (XDG compliant).
func EnvPaths() (shPath, jsonPath, dir string) {
	dir = DataDir()
	return filepath.Join(dir, "env.sh"), filepath.Join(dir, "proxy.json"), dir
}

// Vars builds the ordered proxy env list from config.
// HTTPS :443 TCP goes via Privoxy (HTTP CONNECT) so curl/git/npm work w/o extra flags.
func Vars(cfg config.Config) [][2]string {
	http := "http://" + cfg.PrivoxyAddr
	socks := "socks5h://" + cfg.TorSOCKSAddr
	noProxy := "localhost,127.0.0.1,::1"
	return [][2]string{
		{"HTTP_PROXY", http},
		{"HTTPS_PROXY", http},
		{"http_proxy", http},
		{"https_proxy", http},
		{"ALL_PROXY", socks},
		{"all_proxy", socks},
		{"SOCKS_PROXY", socks},
		{"socks_proxy", socks},
		{"NO_PROXY", noProxy},
		{"no_proxy", noProxy},
	}
}

// RenderShell renders vars for a shell: posix (sh/bash/zsh) or fish.
func RenderShell(cfg config.Config, shell string) string {
	vars := Vars(cfg)
	var b strings.Builder
	b.WriteString("# generated by `torstack env` — do not edit; source this file\n")
	if shell == "fish" {
		for _, kv := range vars {
			fmt.Fprintf(&b, "set -gx %s \"%s\";\n", kv[0], kv[1])
		}
		return b.String()
	}
	for _, kv := range vars {
		fmt.Fprintf(&b, "export %s=\"%s\"\n", kv[0], kv[1])
	}
	return b.String()
}

// BuildProxyFile builds the JSON-serializable proxy description.
func BuildProxyFile(cfg config.Config) ProxyFile {
	vars := map[string]string{}
	for _, kv := range Vars(cfg) {
		vars[kv[0]] = kv[1]
	}
	return ProxyFile{
		HTTPProxy:   vars["HTTP_PROXY"],
		HTTPSProxy:  vars["HTTPS_PROXY"],
		AllProxy:    vars["ALL_PROXY"],
		SocksProxy:  vars["SOCKS_PROXY"],
		NoProxy:     vars["NO_PROXY"],
		SocksAddr:   cfg.TorSOCKSAddr,
		PrivoxyAddr: cfg.PrivoxyAddr,
		ControlAddr: cfg.TorControlAddr,
	}
}

// RenderJSON renders proxy.json content.
func RenderJSON(cfg config.Config) (string, error) {
	pf := BuildProxyFile(cfg)
	data, err := json.MarshalIndent(pf, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data) + "\n", nil
}

// Write writes env.sh + proxy.json to XDG_DATA_HOME/torstack/.
// Returns written paths.
func Write(cfg config.Config) (shPath, jsonPath string, err error) {
	shPath, jsonPath, dir := EnvPaths()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", err
	}
	shell := shellName()
	if err := os.WriteFile(shPath, []byte(RenderShell(cfg, shell)), 0o644); err != nil {
		return "", "", err
	}
	js, err := RenderJSON(cfg)
	if err != nil {
		return "", "", err
	}
	if err := os.WriteFile(jsonPath, []byte(js), 0o644); err != nil {
		return "", "", err
	}
	return shPath, jsonPath, nil
}

func shellName() string {
	sh := os.Getenv("SHELL")
	if strings.Contains(sh, "fish") {
		return "fish"
	}
	return "posix"
}
